[package]
name = "assistd-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
test-support = []

[dependencies]
tokio = { workspace = true, features = ["fs", "io-util", "macros", "process", "rt", "sync", "time"] }
rustix = { workspace = true }
procfs = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true, features = ["stream"] }
dirs = { workspace = true }
futures-util = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
parking_lot = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "net", "rt", "rt-multi-thread"] }

[lints]
workspace = true
