use std::collections::HashSet;
use std::fs::{self, DirBuilder, File, OpenOptions};
use std::io::{self, Write};
use std::net::IpAddr;
use std::ops::RangeInclusive;
use std::os::unix::fs::{DirBuilderExt, OpenOptionsExt, PermissionsExt};
use std::path::{Path, PathBuf};

use assistd_utils::path::tilde_remainder;
use serde::{Deserialize, Serialize};

use crate::chat::ChatConfig;
use crate::compositor::CompositorConfig;
use crate::daemon::DaemonConfig;
use crate::embedding::EmbeddingConfig;
use crate::errors::ConfigError;
use crate::mcp::McpConfig;
use crate::memory::MemoryConfig;
use crate::model::ModelConfig;
use crate::presence::PresenceConfig;
use crate::sleep::SleepConfig;
use crate::timeouts::TimeoutsConfig;
use crate::tools::ToolsConfig;
use crate::tray::{TrayConfig, TrayIconsConfig, TrayNotificationsConfig};
use crate::voice::{SynthesisConfig, VoiceConfig};

const CONFIG_DIR_MODE: u32 = 0o700;
const CONFIG_FILE_MODE: u32 = 0o600;
const GROUP_OR_WORLD_READABLE: u32 = 0o044;

/// Top-level assistd configuration, deserialized from `config.toml`.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
#[serde(default)]
pub struct Config {
    pub model: ModelConfig,
    pub chat: ChatConfig,
    pub voice: VoiceConfig,
    pub compositor: CompositorConfig,
    pub sleep: SleepConfig,
    pub presence: PresenceConfig,
    pub daemon: DaemonConfig,
    pub tools: ToolsConfig,
    pub memory: MemoryConfig,
    pub embedding: EmbeddingConfig,
    pub mcp: McpConfig,
    #[serde(skip)]
    pub timeouts: TimeoutsConfig,
    pub tray: TrayConfig,
}

impl Config {
    /// Validates the cross-field and format constraints that the field
    /// types can't express. Returns every problem found, not just the first.
    pub fn validate(&self) -> Result<(), ConfigError> {
        let mut errors = Vec::new();
        validate_model(&mut errors, &self.model);
        validate_chat(&mut errors, &self.chat, &self.model);
        validate_voice(&mut errors, &self.voice);
        validate_sleep(&mut errors, &self.sleep);
        validate_tools(&mut errors, &self.tools);
        validate_memory(&mut errors, &self.memory);
        validate_embedding(&mut errors, &self.embedding, &self.model);
        validate_mcp(&mut errors, &self.mcp);
        validate_tray_icons(&mut errors, &self.tray.icons);
        validate_tray_notifications(&mut errors, &self.tray.notifications);
        if errors.is_empty() {
            Ok(())
        } else {
            Err(ConfigError::Validation(errors))
        }
    }

    /// `$XDG_CONFIG_HOME/assistd/config.toml`, or `~/.config/assistd/config.toml`.
    /// Errors when no home directory can be found.
    pub fn default_path() -> Result<PathBuf, ConfigError> {
        let config_dir = dirs::config_dir().ok_or(ConfigError::NoConfigDir)?;
        Ok(config_dir.join("assistd/config.toml"))
    }

    /// Loads and deserializes a config from the given TOML file. Keys the
    /// schema doesn't know are skipped, with a warning logged for each; a
    /// warning is also logged if other users can read a file that sets MCP env.
    pub fn load_from_file(path: &Path) -> Result<Self, ConfigError> {
        let content = fs::read_to_string(path).map_err(|source| ConfigError::Read {
            path: path.to_path_buf(),
            source,
        })?;
        let parse_error = |source| ConfigError::Parse {
            path: path.to_path_buf(),
            source,
        };
        let config: Self = toml::from_str(&content).map_err(parse_error)?;
        let raw: toml::Table = toml::from_str(&content).map_err(parse_error)?;
        for key in config.unknown_keys(&raw)? {
            tracing::warn!(
                target: "assistd::config",
                "ignoring unknown key `{key}` in {} (it may be left over from an older assistd; \
                 see config.sample.toml for the current schema)",
                path.display()
            );
        }
        config.warn_if_credentials_exposed(path);
        Ok(config)
    }

    /// Dotted paths of the keys in `raw` that no field of `self` accounts
    /// for, given that `self` was deserialized from `raw`.
    pub fn unknown_keys(&self, raw: &toml::Table) -> Result<Vec<String>, ConfigError> {
        let known = toml::Table::try_from(self)?;
        let mut unknown = Vec::new();
        collect_unknown_keys(raw, &known, "", &mut unknown);
        Ok(unknown)
    }

    /// Writes the default config to `path` as an owner-only file, creating
    /// missing parent directories owner-only. Errors if the file already exists.
    pub fn write_default(path: &Path) -> Result<(), ConfigError> {
        if let Some(parent) = path.parent() {
            create_private_dir_all(parent)?;
        }

        let toml_string = toml::to_string_pretty(&Config::default())?;
        let content = format!(
            "# assistd configuration file\n\
             # Generated by `assistd init-config`\n\n\
             {toml_string}"
        );

        create_private_file(path)?
            .write_all(content.as_bytes())
            .map_err(|source| ConfigError::Write {
                path: path.to_path_buf(),
                source,
            })
    }

    fn exposes_mcp_env(&self, mode: u32) -> bool {
        mode & GROUP_OR_WORLD_READABLE != 0
            && self.mcp.servers.iter().any(|server| !server.env.is_empty())
    }

    fn warn_if_credentials_exposed(&self, path: &Path) {
        let exposed = fs::metadata(path)
            .is_ok_and(|metadata| self.exposes_mcp_env(metadata.permissions().mode()));
        if exposed {
            tracing::warn!(
                target: "assistd::config",
                "{} is readable by other users and sets mcp.servers[].env; \
                 run `chmod 600 {}` to keep those values private",
                path.display(),
                path.display()
            );
        }
    }
}

fn create_private_dir_all(dir: &Path) -> Result<(), ConfigError> {
    DirBuilder::new()
        .recursive(true)
        .mode(CONFIG_DIR_MODE)
        .create(dir)
        .map_err(|source| ConfigError::CreateDir {
            path: dir.to_path_buf(),
            source,
        })
}

fn create_private_file(path: &Path) -> Result<File, ConfigError> {
    OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(CONFIG_FILE_MODE)
        .open(path)
        .map_err(|source| match source.kind() {
            io::ErrorKind::AlreadyExists => ConfigError::AlreadyExists(path.to_path_buf()),
            _ => ConfigError::Write {
                path: path.to_path_buf(),
                source,
            },
        })
}

/// Walks `raw` alongside `known`, the serialized parsed config, which holds
/// every schema key because defaults fill the ones `raw` omits.
fn collect_unknown_keys(
    raw: &toml::Table,
    known: &toml::Table,
    prefix: &str,
    unknown: &mut Vec<String>,
) {
    for (key, raw_value) in raw {
        let path = if prefix.is_empty() {
            key.clone()
        } else {
            format!("{prefix}.{key}")
        };
        match (raw_value, known.get(key)) {
            (_, None) => unknown.push(path),
            (toml::Value::Table(raw_table), Some(toml::Value::Table(known_table))) => {
                collect_unknown_keys(raw_table, known_table, &path, unknown);
            }
            (toml::Value::Array(raw_items), Some(toml::Value::Array(known_items))) => {
                collect_unknown_array_keys(raw_items, known_items, &path, unknown);
            }
            _ => {}
        }
    }
}

fn collect_unknown_array_keys(
    raw_items: &[toml::Value],
    known_items: &[toml::Value],
    path: &str,
    unknown: &mut Vec<String>,
) {
    for (index, items) in raw_items.iter().zip(known_items).enumerate() {
        if let (toml::Value::Table(raw_table), toml::Value::Table(known_table)) = items {
            collect_unknown_keys(raw_table, known_table, &format!("{path}[{index}]"), unknown);
        }
    }
}

fn validate_model(errors: &mut Vec<String>, model: &ModelConfig) {
    if model.name.is_empty() {
        errors.push("model.name must not be empty".into());
    }
    if model.server_binary.as_os_str().is_empty() {
        errors.push("model.server_binary must not be empty".into());
    }
    require_loopback(errors, "model.host", model.host);
}

fn validate_chat(errors: &mut Vec<String>, chat: &ChatConfig, model: &ModelConfig) {
    let history_and_response =
        u64::from(chat.max_history_tokens.get()) + u64::from(chat.max_response_tokens.get());
    if history_and_response > u64::from(model.context_budget()) {
        errors.push(format!(
            "chat.max_history_tokens + chat.max_response_tokens ({history_and_response}) must \
             not exceed 90% of model.context_length ({})",
            model.context_budget()
        ));
    }
    if chat.summary_target_tokens >= chat.max_history_tokens {
        errors.push(
            "chat.summary_target_tokens must be strictly less than chat.max_history_tokens".into(),
        );
    }
    require_in_range(
        errors,
        chat.temperature,
        0.0..=2.0,
        "chat.temperature must be in the range 0.0..=2.0",
    );
    require_in_range(
        errors,
        chat.summary_temperature,
        0.0..=2.0,
        "chat.summary_temperature must be in the range 0.0..=2.0",
    );
    if let Some(top_p) = chat.top_p {
        require_in_range(
            errors,
            top_p,
            0.0..=1.0,
            "chat.top_p must be in the range 0.0..=1.0",
        );
    }
    if let Some(min_p) = chat.min_p {
        require_in_range(
            errors,
            min_p,
            0.0..=1.0,
            "chat.min_p must be in the range 0.0..=1.0",
        );
    }
    if let Some(presence_penalty) = chat.presence_penalty {
        require_in_range(
            errors,
            presence_penalty,
            -2.0..=2.0,
            "chat.presence_penalty must be in the range -2.0..=2.0",
        );
    }
    if chat.reasoning_effort.as_deref() == Some("") {
        errors.push("chat.reasoning_effort must not be empty".into());
    }
}

fn validate_voice(errors: &mut Vec<String>, voice: &VoiceConfig) {
    if voice.enabled {
        let transcription = &voice.transcription;
        require_hf_id(errors, "voice.transcription.model", &transcription.model);
        if transcription.vad_enabled {
            require_hf_id(
                errors,
                "voice.transcription.vad_model",
                &transcription.vad_model,
            );
        }
    }
    if voice.synthesis.enabled {
        validate_synthesis(errors, &voice.synthesis);
    }
}

fn validate_synthesis(errors: &mut Vec<String>, synthesis: &SynthesisConfig) {
    if synthesis.binary_path.as_os_str().is_empty() {
        errors
            .push("voice.synthesis.binary_path must not be empty when synthesis is enabled".into());
    }
    require_hf_id(errors, "voice.synthesis.voice", &synthesis.voice);
    if !synthesis.length_scale.is_finite() || synthesis.length_scale <= 0.0 {
        errors.push("voice.synthesis.length_scale must be a positive, finite number".into());
    }
    if synthesis.max_sentence_chars.get() < 50 {
        errors.push("voice.synthesis.max_sentence_chars must be at least 50".into());
    }
}

fn validate_sleep(errors: &mut Vec<String>, sleep: &SleepConfig) {
    if sleep.idle_to_drowsy_mins > 0
        && sleep.idle_to_sleep_mins > 0
        && sleep.idle_to_sleep_mins <= sleep.idle_to_drowsy_mins
    {
        errors.push(
            "sleep.idle_to_sleep_mins must be greater than sleep.idle_to_drowsy_mins \
             (set either to 0 to disable that transition)"
                .into(),
        );
    }
}

fn validate_tools(errors: &mut Vec<String>, tools: &ToolsConfig) {
    if !tools.scratch.dir.is_absolute() {
        errors.push("tools.scratch.dir must be an absolute path".into());
    }
    if !tools.output.overflow_dir.is_absolute() {
        errors.push("tools.output.overflow_dir must be an absolute path".into());
    }
    if tools.write.writable_paths.is_empty() {
        errors.push(
            "tools.write.writable_paths must not be empty (the write command would be unusable)"
                .into(),
        );
    }
    for entry in &tools.write.writable_paths {
        if tilde_remainder(entry).is_none() && !Path::new(entry).is_absolute() {
            errors.push(format!(
                "tools.write.writable_paths entry {entry:?} must be absolute or start with `~/`"
            ));
        }
    }
}

fn validate_memory(errors: &mut Vec<String>, memory: &MemoryConfig) {
    if memory.enabled && memory.db_path.as_os_str().is_empty() {
        errors.push("memory.db_path must not be empty when memory.enabled".into());
    }
}

fn validate_embedding(errors: &mut Vec<String>, embedding: &EmbeddingConfig, model: &ModelConfig) {
    if !embedding.enabled {
        return;
    }
    require_hf_id(errors, "embedding.model", &embedding.model);
    if embedding.server_binary.as_os_str().is_empty() {
        errors.push("embedding.server_binary must not be empty when embedding is enabled".into());
    }
    require_loopback(errors, "embedding.host", embedding.host);
    if embedding.port == model.port {
        errors.push("embedding.port must differ from model.port (the chat server)".into());
    }
}

fn require_loopback(errors: &mut Vec<String>, key: &str, host: IpAddr) {
    if !host.is_loopback() {
        errors.push(format!(
            "{key} must be a loopback address (127.0.0.0/8 or ::1), got {host}"
        ));
    }
}

fn validate_mcp(errors: &mut Vec<String>, mcp: &McpConfig) {
    if !mcp.enabled {
        return;
    }
    let mut seen_names: HashSet<&str> = HashSet::new();
    for (i, server) in mcp.servers.iter().enumerate() {
        let name = server.name.as_str();
        if name.is_empty() {
            errors.push(format!("mcp.servers[{i}].name must not be empty"));
        } else if !seen_names.insert(name) {
            errors.push(format!(
                "mcp.servers[{i}].name '{name}' is duplicated; names must be unique"
            ));
        }
        if !is_mcp_server_name(name) {
            errors.push(format!(
                "mcp.servers[{i}].name must use only ASCII letters, digits, '_' or '-', \
                 with no '__' and no trailing '_' (becomes the `<name>` in the \
                 LLM-visible tool name `mcp__<name>__<tool>`)"
            ));
        }
    }
}

fn validate_tray_icons(errors: &mut Vec<String>, icons: &TrayIconsConfig) {
    let named = [
        ("active", &icons.active),
        ("sleeping", &icons.sleeping),
        ("listening", &icons.listening),
        ("generating", &icons.generating),
        ("disconnected", &icons.disconnected),
    ];
    for (key, name) in named {
        if name.trim().is_empty() {
            errors.push(format!("tray.icons.{key} must not be empty"));
        }
    }
}

fn validate_tray_notifications(errors: &mut Vec<String>, notifications: &TrayNotificationsConfig) {
    if notifications.enabled && !(500..=60_000).contains(&notifications.auto_hide_ms) {
        errors.push("tray.notifications.auto_hide_ms must be in the range 500..=60000".into());
    }
}

/// Pushes `message` unless `value` lies in `range`; NaN never does.
fn require_in_range(
    errors: &mut Vec<String>,
    value: f32,
    range: RangeInclusive<f32>,
    message: &str,
) {
    if !range.contains(&value) {
        errors.push(message.into());
    }
}

fn require_hf_id(errors: &mut Vec<String>, field: &str, value: &str) {
    if !is_valid_hf_id(value) {
        errors.push(format!(
            "{field} must be of the form '<owner>/<repo>:<file>'"
        ));
    }
}

fn is_valid_hf_id(id: &str) -> bool {
    let Some((repo, file)) = id.split_once(':') else {
        return false;
    };
    if file.is_empty() || file.contains(':') {
        return false;
    }
    let Some((owner, name)) = repo.split_once('/') else {
        return false;
    };
    !owner.is_empty() && !name.is_empty()
}

fn is_mcp_server_name(name: &str) -> bool {
    name.chars().all(is_tool_name_char) && !name.contains("__") && !name.ends_with('_')
}

fn is_tool_name_char(c: char) -> bool {
    c.is_ascii_alphanumeric() || c == '_' || c == '-'
}

#[cfg(test)]
mod tests;
